# Dependencies
markdown:         kramdown
highlighter:      pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]
exclude: [vendor]

# Permalinks
permalink:        pretty

# Setup
title:            '@sroberts'
tagline:          'advanced persistent incident responder'
description:      'intelligentsia in training, network security ninja, pancake visionary, former mixtape master, wannabe coffee specialist, bad guy catcher @ github'
url:              http://sroberts.github.io/
baseurl:          /

author:
  name:           'Scott J Roberts'
  url:            'https://twitter.com/sroberts'
  email:          'scott.roberts@gmail.com'

paginate:         5

# Custom vars
version:          2.1.0

github:
  main:           https://github.com/sroberts/
  repo_url:       https://github.com/sroberts/sroberts.github.io/

twitter:
  main:           https://www.twitter.com/sroberts

linkedin:
  main:           http://www.linkedin.com/in/scottroberts

pgp:
  main:           https://keybase.io/sroberts

rss:
  main:          http://sroberts.github.io/atom.xml

gems:
- jemoji
- jekyll-sitemap
